obs_horizon: 3
exe_horizon: 12
control_hz: 10.0
max_duration_sec: 30.0
start_countdown_sec: 2.0
status_print_hz: 1.0
task_name: put_cup_on_plate
initial_eef_pose_xyz_rpy_deg: [0.0, 0.45, 0.5, 180.0, 0.0, 45.0]
initial_move_duration_sec: 2.0
gripper_forever_closed: false
rand_init_pose: [0.0, 0.0, 0.0]

modality:
  proprioception: true
  rgb_cameras: []
  gelsight_frame: false
  controller_state_max_age_sec: 2.0
  rgb_camera_max_age_sec: 2.0
  gelsight_max_age_sec: 2.0

eval:
  enabled: true
  cameras: []
  stream_cameras: [third]
  video_hz: 10.0

rgb_cameras:
  wrist:
    enabled: true
    backend: orbbec
    stream_name: rgb_wrist
    camera_name: wrist_orbbec_rgb
    serial_number: CP0E753000KA
    color_width: 640
    color_height: 0
    color_format: RGB
    color_fps: 30
    frame_timeout_ms: 200
    save_frames: true
    record_hz: 15.0
  third_person:
    enabled: true
    backend: orbbec
    stream_name: rgb_third_person
    camera_name: third_person_orbbec_rgb
    serial_number: CP0HC530002T
    color_width: 640
    color_height: 0
    color_format: RGB
    color_fps: 30
    frame_timeout_ms: 200
    save_frames: true
    record_hz: 15.0
gelsight:
  enabled: false
