obs_horizon: 2
exe_horizon: 16
control_hz: 10.0
max_duration_sec: 360.0
start_countdown_sec: 2.0
status_print_hz: 1.0
task_name: pencil_insertion
initial_eef_pose_xyz_rpy_deg: [0.06, 0.6, 0.6, 180.0, 0.0, 45.0]
initial_move_duration_sec: 2.0
gripper_forever_closed: true
rand_init_pose: [0.00, 0.00, 0.00]

modality:
  proprioception: true
  rgb_cameras: [wrist]
  gelsight_frame: true
  controller_state_max_age_sec: 2.0
  rgb_camera_max_age_sec: 2.0
  gelsight_max_age_sec: 2.0

eval:
  enabled: true
  cameras: [wrist, gelsight]
  stream_cameras: [third]
  video_hz: 10.0

rgb_cameras:
  wrist:
    enabled: true
    backend: orbbec
    stream_name: rgb_wrist
    camera_name: wrist_orbbec_rgb
    serial_number: CP0E753000KA
    color_width: 1280
    color_height: 0
    color_format: RGB
    color_fps: 30
    frame_timeout_ms: 200
    save_frames: false
    record_hz: 15.0
  third_person:
    enabled: true
    backend: orbbec
    stream_name: rgb_third_person
    camera_name: third_person_orbbec_rgb
    serial_number: CP0HC530002T
    color_width: 640
    color_height: 0
    color_format: RGB
    color_fps: 30
    frame_timeout_ms: 200
    save_frames: false
    record_hz: 15.0

gelsight:
  enabled: true
  camera_name: left_gripper_camera_1
  camera_index: 0
  camera_path: /dev/v4l/by-id/usb-Arducam_Technology_Co.__Ltd._GelSight_Mini_R0B_2BUU-CE3E_2BUUCE3E-video-index0
  device_name_contains: GelSight Mini
  device_serial_number: 2BUUCE3E
  fps: 10
  width: 640
  height: 480
  apply_controls: false
  exposure: null
  contrast: 32
  save_frames: false
  record_hz: 0.0
  buffered_recording: true
  buffer_max_frames: 900
  buffer_chunk_frames: 100
  buffer_overflow_policy: fail_episode

model_input_recording:
  enabled: false
  streams: [rgb_wrist, gelsight]
  format: png
  save_npz: true
