_target_: movement_primitive_diffusion.models.diffusion_model.DiffusionModel
_recursive_: False

defaults:
  - inner_model_config: ???
  - scaling_config: ???
  - _self_

algorithm: diffusion  # 'diffusion' or 'flow_matching'
use_ot_sampler: False  # For flow matching
