_target_: movement_primitive_diffusion.models.flow_matching_model.FlowMatchingModel
_recursive_: False

defaults:
  - inner_model_config: ???
  - _self_

use_ot_sampler: False  # Whether to use optimal transport sampler for x_0
