defaults:
  - _self_
  - task: univtac

name: act
_target_: isp.workspace.train_act_workspace.TrainActWorkspace

shape_meta: ${task.shape_meta}
exp_name: "default"

dataset_root: /mnt/pfs/rmgf7p/tanzl/Kenny/code/visuotactile/data/UniVTAC
data_split: clean
task_name: lift_can
n_demo: 100
horizon: 10
n_obs_steps: 1
n_action_steps: 10
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
dataset: isp.dataset.univtac_replay_image_dataset.UniVTACReplayImageDataset

policy:
  _target_: isp.policy.act_policy.ACTPolicyWrapper

  shape_meta: ${shape_meta}
  max_timesteps: 500
  temporal_agg: false
  n_envs: 1
  horizon: ${horizon}

dataloader:
  batch_size: 64
  num_workers: 16
  shuffle: True
  pin_memory: True
  persistent_workers: True

val_dataloader:
  batch_size: 64
  num_workers: 16
  shuffle: False
  pin_memory: True
  persistent_workers: True

training:
  device: "cuda:0"
  seed: 0
  debug: False
  resume: True
  num_epochs: 300
  checkpoint_every: ${eval:'1000 / ${n_demo}'}
  val_every: 1
  max_train_steps: null
  max_val_steps: null
  log_every_steps: 10
  cudnn_benchmark: True
  tqdm_interval_sec: 1.0

logging:
  project: isp_${task_name}
  entity: roccendalanda-cuhk
  resume: True
  mode: online
  name: act_demo${n_demo}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: val_loss
    mode: min
    k: 2
    format_str: 'epoch={epoch:04d}-val_loss={val_loss:.6f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_demo${n_demo}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}_demo${n_demo}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_demo${n_demo}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}_demo${n_demo}
    subdir: ${hydra.job.num}
