name: univtac_bimanual

shape_meta: &shape_meta
  obs:
    robot0_eye_in_hand_image:
      shape: [3, 224, 224]
      type: rgb
    robot1_eye_in_hand_image:
      shape: [3, 224, 224]
      type: rgb
    robot0_tactile_left_image:
      shape: [3, 224, 224]
      type: tactile_rgb
    robot1_tactile_right_image:
      shape: [3, 224, 224]
      type: tactile_rgb
    qpos:
      shape: [20]
      type: low_dim
  action:
    shape: [20]

abs_action: &abs_action false

dataset:
  _target_: ${dataset}
  shape_meta: *shape_meta
  dataset_root: ${dataset_root}
  task_name: ${task_name}
  split: ${data_split}
  n_demo: ${n_demo}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  use_legacy_normalizer: false
  normalization_mode: default
  use_cache: true
  seed: 42
  val_ratio: 0.2
