task_name: pencil_insertion
initial_eef_pose_xyz_rpy_deg: [0.06, 0.6, 0.6, 180.0, 0.0, 45.0]
initial_move_duration_sec: 2.0
home_joint_positions_rad: [1.2096, 0.1493, 0.287, -1.4945, -0.0111, 1.6255, 0.7401]
home_joint_duration_sec: 4.0
home_joint_tolerance_rad: 0.05
gripper_forever_closed: true
rand_init_pose: [0.01, 0.01, 0.01]

collection:
  controller_state_poll_hz: 60.0
  quest_message_timeout_sec: 2.0
  require_quest_connection: true
  start_countdown_sec: 2.0
  status_print_hz: 1.0
  record_raw_quest_messages: true
  initial_pose_tolerance_m: 0.015
  initial_pose_tolerance_deg: 10.0
  initial_pose_settle_timeout_sec: 8.0
  initial_pose_settle_dwell_sec: 0.3

modality:
  proprioception: true
  rgb_cameras: [wrist]
  gelsight_frame: true
  controller_state_max_age_sec: 2.0
  rgb_camera_max_age_sec: 2.0
  gelsight_max_age_sec: 2.0

rgb_cameras:
  wrist:
    enabled: true
    backend: orbbec
    stream_name: rgb_wrist
    camera_name: wrist_orbbec_rgb
    serial_number: CP0E753000KA
    color_width: 640
    color_height: 0
    color_format: RGB
    color_fps: 30
    frame_timeout_ms: 200
    save_frames: true
    record_hz: 15.0
  third_person:
    enabled: true
    backend: orbbec
    stream_name: rgb_third_person
    camera_name: third_person_orbbec_rgb
    serial_number: CP0HC530002T
    color_width: 640
    color_height: 0
    color_format: RGB
    color_fps: 30
    frame_timeout_ms: 200
    save_frames: false
    record_hz: 15.0

gelsight:
  enabled: true
  camera_name: left_gripper_camera_1
  camera_index: 0
  camera_path: /dev/v4l/by-id/usb-Arducam_Technology_Co.__Ltd._GelSight_Mini_R0B_2BUU-CE3E_2BUUCE3E-video-index0
  device_name_contains: GelSight Mini
  device_serial_number: 2BUUCE3E
  fps: 10
  width: 640
  height: 480
  apply_controls: false
  exposure: null
  contrast: 32
  save_frames: true
  record_hz: 0.0
  buffered_recording: true
  buffer_max_frames: 900
  buffer_chunk_frames: 100
  buffer_overflow_policy: fail_episode
