host: 0.0.0.0
port: 8084
controller_host: 10.0.0.1
controller_port: 8093
controller_request_timeout_sec: 0.3
loop_hz: 60.0
command_hz: 20.0
trigger_enable_button_index: 4
min_gripper_width: 0.0
max_gripper_width: 0.078
gripper_velocity: 0.1
force_limit: 7.0
width_gamma: 1.5
width_deadband_m: 0.0015
command_record_hz: 0.0
quest_message_record_hz: 0.0
status_history_len: 240
collect_root: /home/zhenya/kenny/visuotact/vt_franka/robot_workspace/data/gripper_testbed
require_enable_button: true
