type: replay
checkpoint_path: null
config:
  episode_dir: /home/zhenya/kenny/visuotact/vt_franka/robot_workspace/data/collect/pencil_insertion/episodes/episode_0000
  chunk_size: 8
  skip_gripper: false
