type: visuotactile
checkpoint_path: /home/zhenya/kenny/visuotact/vt_dual_franka/robot_workspace/data/checkpoints/pencil_insertion/vista_so2
config:
  model: vista_so2
  task_name: pencil_insertion
  device: cuda
  checkpoint_file: epoch=209.ckpt
