type: visuotactile
checkpoint_path: /home/zhenya/kenny/visuotact/vt_franka/robot_workspace/data/checkpoints/usb_insertion/vista_so3
config:
  model: vista_so3
  task_name: usb_insertion
  device: cuda
  checkpoint_file: epoch=119.ckpt
