type: visuotactile
checkpoint_path: /home/zhenya/kenny/visuotact/vt_franka/robot_workspace/data/checkpoints/erasing/vista_so3
config:
  model: vista_so3
  task_name: erasing
  device: cuda
  checkpoint_file: epoch=209.ckpt
