from __future__ import annotations

import os
import torch
import numpy as np
import pickle
import argparse
import json
import yaml
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

SCRIPT_DIR = Path(__file__).resolve().parent

from copy import deepcopy
from tqdm import tqdm

from .utils import load_data  # data functions
from .utils import compute_dict_mean, set_seed, detach_dict  # helper functions
from .act_policy import ACTPolicy, CNNMLPPolicy

import IPython
e = IPython.embed


def main(args):
    set_seed(1)
    # command line parameters
    is_eval = args["eval"]
    ckpt_dir = args["ckpt_dir"]
    policy_class = args["policy_class"]
    onscreen_render = args["onscreen_render"]
    task_name = args["task_name"]
    batch_size_train = args["batch_size"]
    batch_size_val = args["batch_size"]

    # get task parameters
    explicit_dataset_dir = args.get("dataset_dir")
    explicit_num_episodes = args.get("num_episodes")
    is_sim = bool(explicit_dataset_dir) or task_name[:4] == "sim-"
    if explicit_dataset_dir:
        dataset_dir = explicit_dataset_dir
        if explicit_num_episodes is None or explicit_num_episodes <= 0:
            explicit_num_episodes = len(sorted(Path(dataset_dir).glob("episode_*.hdf5")))
        task_config = {
            "dataset_dir": dataset_dir,
            "num_episodes": explicit_num_episodes,
            "episode_len": 1000,
        }
    elif is_sim:
        # TacArena: load from JSON file generated by process_data.py
        SIM_TASK_CONFIGS_PATH = SCRIPT_DIR / "SIM_TASK_CONFIGS.json"
        with open(SIM_TASK_CONFIGS_PATH, "r") as f:
            SIM_TASK_CONFIGS = json.load(f)
        task_config = SIM_TASK_CONFIGS[task_name]
    else:
        from aloha_scripts.constants import TASK_CONFIGS
        task_config = TASK_CONFIGS[task_name]
    
    dataset_dir = task_config["dataset_dir"]
    num_episodes = task_config["num_episodes"]
    episode_len = task_config["episode_len"]
    camera_names = args["camera_names"]

    # fixed parameters
    if policy_class == "CNNMLP":
        policy_config = {
            "lr": args["lr"],
            "lr_backbone": args["lr_backbone"],
            "backbone": args["backbone"],
            "num_queries": 1,
            "camera_names": camera_names,
        }
    elif policy_class != "ACT":
        raise NotImplementedError

    state_dim = args["state_dim"]
    tactile_names = args["tactile_names"]
    chunk_size = args["chunk_size"]
    config = {
        "num_epochs": args.get("num_epochs"),
        "ckpt_dir": ckpt_dir,
        "episode_len": episode_len,
        "state_dim": state_dim,
        "lr": args["lr"],
        "policy_class": policy_class,
        "onscreen_render": onscreen_render,
        "policy_config": args,
        "task_name": task_name,
        "seed": args["seed"],
        "temporal_agg": False,
        "camera_names": camera_names,
        "real_robot": not is_sim,
        "save_freq": args['save_freq'],
        "num_steps": args.get("num_steps"),
    }

    if is_eval:
        print("=" * 60)
        print("TacArena ACT Policy Evaluation")
        print("=" * 60)
        print("Please use the unified evaluation script:")
        print("  python scripts/eval_policy.py policy/ACT/deploy_policy_{task_name}.yml")
        print("")
        print("Note: TacArena uses IsaacLab simulation environment for evaluation.")
        print("      The eval_bc() function is for RoboTwin's MuJoCo environment.")
        print("=" * 60)
        exit()

    train_dataloader, val_dataloader, stats, _ = load_data(dataset_dir, num_episodes, camera_names, tactile_names, batch_size_train, batch_size_val, chunk_size)

    # save dataset stats
    if not os.path.isdir(ckpt_dir):
        os.makedirs(ckpt_dir)
    args_path = os.path.join(ckpt_dir, "args.json")
    with open(args_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)
    stats_path = os.path.join(ckpt_dir, f"dataset_stats.pkl")
    with open(stats_path, "wb") as f:
        pickle.dump(stats, f)
    best_ckpt_info = train_bc(train_dataloader, val_dataloader, config)
    best_epoch, min_val_loss, best_state_dict = best_ckpt_info

    # save best checkpoint
    ckpt_path = os.path.join(ckpt_dir, f"policy_best.ckpt")
    torch.save(best_state_dict, ckpt_path)
    summary_path = os.path.join(ckpt_dir, "train_summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "best_epoch": int(best_epoch),
                "min_val_loss": float(min_val_loss),
                "best_checkpoint": ckpt_path,
            },
            f,
            indent=2,
        )
    print(f"Best ckpt, val loss {min_val_loss:.6f} @ epoch{best_epoch}")


def make_policy(policy_class, policy_config):
    if policy_class == "ACT":
        policy = ACTPolicy(policy_config)
    elif policy_class == "CNNMLP":
        policy = CNNMLPPolicy(policy_config)
    else:
        raise NotImplementedError
    return policy


def make_optimizer(policy_class, policy):
    if policy_class == "ACT":
        optimizer = policy.configure_optimizers()
    elif policy_class == "CNNMLP":
        optimizer = policy.configure_optimizers()
    else:
        raise NotImplementedError
    return optimizer


def forward_pass(data, policy):
    cam_data, tac_data, qpos_data, action_data, is_pad = data
    cam_data, tac_data, qpos_data, action_data, is_pad = (
        cam_data.cuda(),
        tac_data.cuda(),
        qpos_data.cuda(),
        action_data.cuda(),
        is_pad.cuda(),
    )
    return policy(qpos_data, cam_data, tac_data, action_data, is_pad)  # TODO remove None


def _scalar(value):
    if hasattr(value, "item"):
        return float(value.item())
    return float(value)


def _prefixed_scalars(prefix, summary):
    return {f"{prefix}_{key}": _scalar(value) for key, value in summary.items()}


def save_best_artifacts(
    ckpt_dir,
    *,
    epoch,
    global_step,
    train_summary,
    val_summary,
    state_dict,
):
    train_loss = train_summary["loss"]
    val_loss = val_summary["loss"]
    ckpt_path = os.path.join(ckpt_dir, "policy_best.ckpt")
    torch.save(state_dict, ckpt_path)
    payload = {
        "best_epoch": int(epoch),
        "global_step": int(global_step),
        "min_val_loss": _scalar(val_loss),
        "train_loss": _scalar(train_loss),
        "best_checkpoint": ckpt_path,
    }
    payload.update(_prefixed_scalars("train", train_summary))
    payload.update(_prefixed_scalars("val", val_summary))
    summary_path = os.path.join(ckpt_dir, "train_summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")
    info_path = os.path.join(ckpt_dir, "best.info.json")
    info = {
        "checkpoint": "policy_best.ckpt",
        "monitor_key": "val_loss",
        "monitor_value": _scalar(val_loss),
        "mode": "min",
        "epoch": int(epoch),
        "global_step": int(global_step),
    }
    info.update(_prefixed_scalars("train", train_summary))
    info.update(_prefixed_scalars("val", val_summary))
    with open(info_path, "w", encoding="utf-8") as f:
        json.dump(
            info,
            f,
            indent=2,
            sort_keys=True,
        )
        f.write("\n")


def train_bc(train_dataloader, val_dataloader, config):
    ckpt_dir = config["ckpt_dir"]
    seed = config["seed"]
    policy_class = config["policy_class"]
    policy_config = config["policy_config"]

    set_seed(seed)

    policy = make_policy(policy_class, policy_config)
    policy.cuda()
    optimizer = make_optimizer(policy_class, policy)

    train_history = []
    validation_history = []
    min_val_loss = np.inf
    best_ckpt_info = None

    step_count = 0
    num_steps = config.get("num_steps")
    num_epochs = config.get("num_epochs")
    if num_steps is None and num_epochs is None:
        num_steps = 4000
    if num_steps is not None:
        num_steps = int(num_steps)
    if num_epochs is not None:
        num_epochs = int(num_epochs)
    epoch = 0
    loss_log_path = os.path.join(ckpt_dir, "loss_history.jsonl")
    open(loss_log_path, "w", encoding="utf-8").close()

    progress_total = num_steps if num_steps is not None else num_epochs
    pbar = tqdm(total=progress_total, leave=False)
    while True:
        policy.train()
        optimizer.zero_grad()
        for batch_idx, data in enumerate(train_dataloader):
            forward_dict = forward_pass(data, policy)
            # backward
            loss = forward_dict["loss"]
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            train_history.append(detach_dict(forward_dict))

            pbar.set_postfix({'epoch': epoch, 'loss': loss.item()})
            if num_steps is not None:
                pbar.update(1)

            step_count += 1
            if num_steps is not None and step_count >= num_steps:
                break

        epoch_train_summary = compute_dict_mean(train_history[(batch_idx + 1) * epoch:(batch_idx + 1) * (epoch + 1)])
        epoch_train_loss = epoch_train_summary["loss"]

        train_summary_string = ""
        for k, v in epoch_train_summary.items():
            train_summary_string += f"{k}: {v.item():.3f} "

        with torch.inference_mode():
            policy.eval()
            epoch_dicts = []
            for batch_idx, data in enumerate(val_dataloader):
                forward_dict = forward_pass(data, policy)
                epoch_dicts.append(forward_dict)

            epoch_val_summary = compute_dict_mean(epoch_dicts)
            validation_history.append(epoch_val_summary)

            epoch_val_loss = epoch_val_summary["loss"]
            if epoch_val_loss < min_val_loss:
                min_val_loss = epoch_val_loss
                best_state_dict = deepcopy(policy.state_dict())
                best_ckpt_info = (epoch, min_val_loss, best_state_dict)
                save_best_artifacts(
                    ckpt_dir,
                    epoch=epoch,
                    global_step=step_count,
                    train_summary=epoch_train_summary,
                    val_summary=epoch_val_summary,
                    state_dict=best_state_dict,
                )

        eval_summary_string = ""
        for k, v in epoch_val_summary.items():
            eval_summary_string += f"{k}: {v.item():.3f} "

        with open(loss_log_path, "a", encoding="utf-8") as f:
            row = {
                "epoch": int(epoch),
                "global_step": int(step_count),
                "best_val_loss": float(min_val_loss.item()),
            }
            row.update(_prefixed_scalars("train", epoch_train_summary))
            row.update(_prefixed_scalars("val", epoch_val_summary))
            json.dump(
                row,
                f,
            )
            f.write("\n")

        if num_steps is None:
            pbar.update(1)

        if num_steps is not None and step_count >= num_steps:
            break
        epoch += 1
        if num_steps is None and epoch >= num_epochs:
            break
    pbar.close()

    best_epoch, min_val_loss, best_state_dict = best_ckpt_info
    print(f"Training finished:\nSeed {seed}, val loss {min_val_loss:.6f} at epoch {best_epoch}")

    # save training curves
    plot_history(train_history, validation_history, epoch, ckpt_dir, seed)

    return best_ckpt_info


def plot_history(train_history, validation_history, num_epochs, ckpt_dir, seed):
    # save training curves
    x_span = max(int(num_epochs) - 1, len(validation_history) - 1, 1)
    for key in train_history[0]:
        plot_path = os.path.join(ckpt_dir, f"train_val_{key}_seed_{seed}.png")
        plt.figure()
        train_values = [summary[key].item() for summary in train_history]
        val_values = [summary[key].item() for summary in validation_history]
        plt.plot(
            np.linspace(0, x_span, len(train_history)),
            train_values,
            label="train",
        )
        plt.plot(
            np.linspace(0, x_span, len(validation_history)),
            val_values,
            label="validation",
        )
        # plt.ylim([-0.1, 1])
        plt.tight_layout()
        plt.legend()
        plt.title(key)
        plt.savefig(plot_path)
        plt.close()
    print(f"Saved plots to {ckpt_dir}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--eval", action="store_true")
    parser.add_argument("--onscreen_render", action="store_true")
    parser.add_argument("--ckpt_dir", action="store", type=str, help="ckpt_dir", required=True)
    parser.add_argument("--task_name", action="store", type=str, help="task_name", required=True)
    parser.add_argument("--config_path", action="store", type=str, help="config_path", required=True)
    parser.add_argument("--seed", action="store", type=int, help="seed", required=True)
    parser.add_argument("--dataset_dir", action="store", type=str, help="Explicit processed dataset dir", required=False)
    parser.add_argument("--num_episodes", action="store", type=int, help="Number of episodes to train on", required=False)
    parser.add_argument("--tactile_ckpt", action="store", type=str, help="Override tactile checkpoint path", required=False)

    args = parser.parse_args()
    with open(args.config_path, 'r') as f:
        config_args = yaml.load(f, Loader=yaml.FullLoader)
    for key, value in vars(args).items():
        if value is not None:
            config_args[key] = value
    main(config_args)
